version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "5000:5000"
    # tty: trueg
    command: python /app/Style-Bert-VITS2-JVNW/server_fastapi.py