version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/work
    ports:
      - "7878:7860"
    tty: true
    command: python app.py --share --server-name 0.0.0.0

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]