version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/work
    ports:
      - "8000:8000"
      - "5000:5000"
    # tty: true
    command: python /app/Style-Bert-VITS2-JVNW/server_fastapi.py